### ISSUE TITLE
Example config needs updating

### ISSUE THREAD

**Issue by billfarrow** [sudoer/flashback#2]
sudo /usr/sbin/flashback -d
2015-02-17 23:03:45 pidfile '/var/run/flashback.pid' found... better look for a running process
2015-02-17 23:03:45 pid 23886 not found, continuing
2015-02-17 23:03:45 reading global config file '/etc/flashback.conf'
2015-02-17 23:03:45 config file '/etc/flashback.conf' found
2015-02-17 23:03:45 /etc/flashback.conf: topDir = /backup
2015-02-17 23:03:45 /etc/flashback.conf topDir:/backup
2015-02-17 23:03:45 raw topDir:/backup
2015-02-17 23:03:45  - /etc/flashback.conf: topDir=/backup >> STRING >> topDir=/backup
2015-02-17 23:03:45 writing status file and queue file
2015-02-17 23:03:45 2015-02-17 23:03:45 : not yet started
2015-02-17 23:03:45 NOT YET STARTED
2015-02-17 23:03:45 
Traceback (most recent call last):
  File "/usr/sbin/flashback", line 847, in <module>
    main()
  File "/usr/sbin/flashback", line 815, in main
    if os.path.isfile(defaults['helper']):
KeyError: 'helper'

**Comment by sudoer** [comment]
Fixed in c36917af5037abb5b401c53bf57f39e09393ae4e

**Comment by sudoer** [comment]
The "helper" config option is OPTIONAL, and the code should handle it not being set.

**Comment by sudoer** [comment]
Added a much better, annotated, example config file.
